# Generated by Django 3.2.7 on 2021-09-15 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcpharma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dateRegistered',
            field=models.DateField(default=datetime.datetime(2021, 9, 15, 13, 53, 43, 152749)),
        ),
    ]
